language: php

php:
  - 7.1
  - 7.0

install:
   - mkdir -p build/bin
   - mkdir -p build/logs
   - curl -sS https://getcomposer.org/installer | php -- --install-dir=./build/bin
   - php ./build/bin/composer.phar install

script:
   - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml tests/

